blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('blog/', views.blog, name='article_blog'),
    path('blog/<int:id>/', views.blog_detail, name='blog-detail'),
    path('example/', views.example),

]

info/urls.py
from django.urls import path
from . import views

app_name='info'
urlpatterns = [
    path('', views.home, name='about'),
    path('contact/', views.contact, name='contacts'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('info.urls')),
    path('',include('blog.urls')),
    path('user/',include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),

]

blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
  title=models.CharField(max_length=20)
  description=models.TextField()
  content=models.TextField()
  show=models.BooleanField(default=True)
  view_count=models.IntegerField()
  image=models.ImageField(null=True, blank=True)
  created=models.DateField(auto_now_add=True)

  def __str__(self):
      return self.title

info/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=50)
    name=models.CharField(max_length=50)
    name=models.CharField(max_length=50)
    name=models.CharField(max_length=50)

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.models import User
import re

username_compiler=re.compile(r'^\w{5,}$')

class RegisterForm(forms.Form):
    first_name=forms.CharField()
    last_name=forms.CharField()
    username=forms.CharField()
    email=forms.EmailField()
    password=forms.CharField(widget=forms.PasswordInput)
    password_repeat=forms.CharField(widget=forms.PasswordInput)
    def save(self):
        first_name=self.cleaned_data.get('first_name')
        last_name=self.cleaned_data.get('last_name')
        username=self.cleaned_data.get('username')
        email=self.cleaned_data.get('email')
        password=self.cleaned_data.get('password')

        user=User.objects.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            password=password
        )
        return user
    def clean_username(self):
        username=self.cleaned_data.get('username')   
        if not username_compiler.match(username):
            raise forms.ValidationError('username is incorrect')
        elif User.objects.filter(username=username).exists():
            raise forms.ValidationError('this is an existing username')
        
        return username
        
    def clean_email(self):
        email=self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            return forms.ValidationError('this email is already exists')
        

    def clean(self):
        super().clean()
        password=self.cleaned_data.get('password')
        password_repeat=self.cleaned_data.get('password_repeat')
        if password and password_repeat and password != password_repeat:
            raise forms.ValidationError('password is not correct')
        
class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)



    

blog/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def blog(request):
    articles=Article.objects.all() 
    return render(request,'blog.html', context={'articles':articles})


def blog_detail(request,id):
    article=Article.objects.get(id=id)
    return render(request,'blog-detail.html', context={'article':article})


def example(request):
        users=[
        {'name':'orxan','age':27,'job': 'Sofware Developer'},
        {'name':'eli','age':24,'job': 'Sofware Developer'},
        {'name':'aysel','age':21,'job': 'Sofware Developer'},
        {'name':'senan','age':23,'job': 'Sofware Developer'},
        ]
        return render(request,'example.html',context={'users':users})

info/views.py
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
    return render(request,'home.html')


def contact(request):
    return render(request,'contact.html')

def confirm_contact(request):
    if request.method == "GET":
        return redirect('info:contact')
    elif request.method == "POST":
        return redirect('info:contact')

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
# Create your views here.
def login_view(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=User.objects.filter(username=username).first()
            if user and user.check_password(password):
                login(request,user)
                return redirect('info:home')
            return render(request, 'login.html',context={'form':form, 'invalid_credentials':True})
        return render(request, 'login.html',context={'form':form})
    else:
        form=LoginForm()
        return render(request, 'login.html')

def register_view(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('info:html')
        return render(request, 'register.html', context={'form':form})
    else:
       form=RegisterForm
       return render(request, 'register.html')

def logout_view(request):
    logout(request)
    return redirect('user:login')

blog/templates/blog-detail.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}

{% static 'img/post-bg.jpg' as blog_bg %}
{% include 'includes/banner.html'  with banner_image=blog_bg banner_title='Details' %}

<!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h1>{{article.title}}</h1>

                    <h5>{{article.description}}</h5>

                    <h2>{{article.created}}</h2>

                    <a href="#">
                        <img class="img-responsive" width='600px' height='500px' src={{article.image.url}} alt="">
                    </a>
                    
                </div>
            </div>
        </div>
    </article>

    {% endblock main %}

blog/templates/blog.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}

{% static 'img/post-bg.jpg' as blog_bg %}
{% include 'includes/banner.html'  with banner_image=blog_bg banner_title='Blog page' banner_description='welcome to blog page' %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
               {% for article in articles %}
               <div class="post-preview">
                <a href="{% url 'blog:blog-detail' id=article.id %}">
                    <h2 class="post-title">
                        {{article.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{article.description |truncatechars:25}}
                    </h3>
                </a>
                <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on {{article.created}} </p>
            </div>
               
               {% endfor %}
               
              
                <hr>

                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>



    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock main %}
   

blog/templates/example.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>


<body>
    
  {% for user in users  %}
  {% if forloop.first %}
  
  <div style='background-color:red'>

      <h1>{{user.name}}</h1>
      <h1>{{user.job |truncatechars:7}}</h1>
      <h1>{{user.age}}</h1>

  </div>

  {% elif forloop.last %}
  <div style='background-color:orange'>

    <h1>{{user.name}}</h1>
    <h1>{{user.job |truncatechars:7}}</h1>
    <h1>{{user.age}}</h1>

</div>

  {% endif %}



  
  
  {% endfor %}  
</body>
</html>

info/templates/contact.html
{% extends 'layout.html' %}
{% load static %}






{% block main %}

{% static 'img/contact-bg.jpg' as contact_bg %}
{% include 'includes/banner.html'  with banner_image=contact_bg banner_title='Contact page' banner_description='welcome to contact page' %}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
            <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
            <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
            <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Name</label>
                        <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Email Address</label>
                        <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Phone Number</label>
                        <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Message</label>
                        <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-default">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock main %}
    <!-- Main Content -->
    

    <hr>

    <!-- Footer -->
   

info/templates/home.html
{% extends 'layout.html' %}
{% load static %}



    <!-- Main Content -->
   
{% block main %}
{% static 'img/home-bg.jpg' as home_bg %}
{% include 'includes/banner.html'  with banner_image=home_bg banner_title='Home page' banner_description='welcome to home page' %}

 <div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
        </div>
    </div>
</div>
{% endblock main %}
    <hr>


   

templates/includes/banner.html
<header class="intro-header" style="background-image: url('{{banner_image}}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>{{banner_title}}</h1>
                    <hr class="small">
                    <span class="subheading">{{banner_description}}</span>
                </div>
            </div>
        </div>
    </div>
</header>

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - About</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'info:about' %}">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'info:about' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:article_blog' %}">Sample Post</a>
                    </li>
                    <li>
                        <a href="{% url 'info:contacts' %}">Contact</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'user:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'user:login' %}">Login</a>

                    </li>
                    <li>
                        <a href="{% url 'user:register' %}">Register</a>
                    </li>
                    
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {% comment %} <header class="intro-header" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Home</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header> {% endcomment %}

    {% block main %}{% endblock main %}

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

user/templates/login.html
{% extends 'layout.html' %}
{% load static %}
{% block main %}


{% static 'img/home-bg.jpg' as home_bg %}
{% include 'includes/banner.html'  with banner_image=home_bg banner_title='Login page' banner_description='welcome to login page' %}

<div class='container'>
    <div class='row'>
        <div class='col-lg-12 text-center'>
            <div>
                <h2>LOGIN</h2>
            </div>
            {% if invalid_credentials %}
            <h1 class='text-danger'> Username or password is wrong  </h1>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                {{form.as_div}}
                <input type="submit">
            </form>
        </div>
    </div>
</div>

{% endblock main %}

user/templates/register.html
{% extends 'layout.html' %}
{% load static %}
{% block main %}

{% static 'img/home-bg.jpg' as home_bg %}
{% include 'includes/banner.html'  with banner_image=home_bg banner_title='Register page' banner_description='welcome to register page' %}

<div class='container'>
    <div class='row'>
        <div class='col-lg-12 text-center'>
            <div>
                <h2>REGISTER</h2>
            </div>
            <form method="POST">
                {% csrf_token %}
                {{form.as_div}}
                <input type="submit">
            </form>
        </div>
    </div>
</div>

{% endblock main %}